### ISSUE TITLE
any link with https://github.com/nipy/heudiconv at this stage ? 

### ISSUE THREAD

**Issue by jbpoline** [jooh/Dcm2Bids#2]
Just curious on how these two can dovetail with each others

**Comment by jooh** [comment]
There are no links at present. You don't need nipype or Heudiconv to run
dcm2bids.

Heudiconv is solves a more general problem (ie, not just bids format), but
pays a price in terms of complexity and more dependencies.

I found it much easier to get Christophe's version of dcm2bids up and
running, so that's what I kept building on.


On 11 Oct 2017 20:59, "Jean-Baptiste Poline" <notifications@github.com>
wrote:

Just curious on how these two can dovetail with each others

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jooh/Dcm2Bids/issues/2>, or mute the thread

**Comment by jbpoline** [comment]
Thanks !
JB
